// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eV7Xi9hgseajGR8GcVFgnT
// Component: yu4cL-EFIGe4C
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_clove_website.module.css"; // plasmic-import: eV7Xi9hgseajGR8GcVFgnT/projectcss
import * as sty from "./PlasmicMenuIcon.module.css"; // plasmic-import: yu4cL-EFIGe4C/css

import MenuBlack24DpsvgIcon from "./icons/PlasmicIcon__MenuBlack24Dpsvg"; // plasmic-import: iN76y7fFcsgbra/icon
import XIcon from "./icons/PlasmicIcon__X"; // plasmic-import: oqstc9Cslcu5a8/icon

export type PlasmicMenuIcon__VariantMembers = {
  open: "open";
};

export type PlasmicMenuIcon__VariantsArgs = {
  open?: SingleBooleanChoiceArg<"open">;
};

type VariantPropType = keyof PlasmicMenuIcon__VariantsArgs;
export const PlasmicMenuIcon__VariantProps = new Array<VariantPropType>("open");

export type PlasmicMenuIcon__ArgsType = {};
type ArgPropType = keyof PlasmicMenuIcon__ArgsType;
export const PlasmicMenuIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicMenuIcon__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMenuIconProps {
  open?: SingleBooleanChoiceArg<"open">;
  className?: string;
}

function PlasmicMenuIcon__RenderFunc(props: {
  variants: PlasmicMenuIcon__VariantsArgs;
  args: PlasmicMenuIcon__ArgsType;
  overrides: PlasmicMenuIcon__OverridesType;
  dataFetches?: PlasmicMenuIcon__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {(hasVariant(variants, "open", "open") ? false : true) ? (
        <MenuBlack24DpsvgIcon
          className={classNames(defaultcss.all, sty.svg__wwVFy, {
            [sty.svg__open__wwVFyXvVcB]: hasVariant(variants, "open", "open")
          })}
          role={"img"}
        />
      ) : null}
      {(hasVariant(variants, "open", "open") ? true : false) ? (
        <XIcon
          className={classNames(defaultcss.all, sty.svg__cXz7B, {
            [sty.svg__open__cXz7BXvVcB]: hasVariant(variants, "open", "open")
          })}
          role={"img"}
        />
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenuIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenuIcon__VariantsArgs;
    args?: PlasmicMenuIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMenuIcon__Fetches;
  } & Omit<PlasmicMenuIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMenuIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMenuIcon__ArgProps,
      internalVariantPropNames: PlasmicMenuIcon__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMenuIcon__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuIcon";
  } else {
    func.displayName = `PlasmicMenuIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuIcon = Object.assign(
  // Top-level PlasmicMenuIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMenuIcon
    internalVariantProps: PlasmicMenuIcon__VariantProps,
    internalArgProps: PlasmicMenuIcon__ArgProps
  }
);

export default PlasmicMenuIcon;
/* prettier-ignore-end */
