// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eV7Xi9hgseajGR8GcVFgnT
// Component: ys1dDALBqW2Dr
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import SubmitButton from "../../SubmitButton"; // plasmic-import: srr7ZVIUQAh-6/component
import FormThankYou from "../../FormThankYou"; // plasmic-import: -HcGzCHHRJliz/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_clove_website.module.css"; // plasmic-import: eV7Xi9hgseajGR8GcVFgnT/projectcss
import * as sty from "./PlasmicContactForm.module.css"; // plasmic-import: ys1dDALBqW2Dr/css

export type PlasmicContactForm__VariantMembers = {
  submitted: "submitted";
};

export type PlasmicContactForm__VariantsArgs = {
  submitted?: SingleBooleanChoiceArg<"submitted">;
};

type VariantPropType = keyof PlasmicContactForm__VariantsArgs;
export const PlasmicContactForm__VariantProps = new Array<VariantPropType>(
  "submitted"
);

export type PlasmicContactForm__ArgsType = {};
type ArgPropType = keyof PlasmicContactForm__ArgsType;
export const PlasmicContactForm__ArgProps = new Array<ArgPropType>();

export type PlasmicContactForm__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  name?: p.Flex<"input">;
  nameError?: p.Flex<"div">;
  email?: p.Flex<"input">;
  emailError?: p.Flex<"div">;
  phone?: p.Flex<"input">;
  phoneError?: p.Flex<"div">;
  message?: p.Flex<"textarea">;
  messageError?: p.Flex<"div">;
  submitButton?: p.Flex<typeof SubmitButton>;
  formThankYou?: p.Flex<typeof FormThankYou>;
};

export interface DefaultContactFormProps {
  submitted?: SingleBooleanChoiceArg<"submitted">;
  className?: string;
}

function PlasmicContactForm__RenderFunc(props: {
  variants: PlasmicContactForm__VariantsArgs;
  args: PlasmicContactForm__ArgsType;
  overrides: PlasmicContactForm__OverridesType;
  dataFetches?: PlasmicContactForm__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {(hasVariant(variants, "submitted", "submitted") ? false : true) ? (
        <p.Stack
          as={"div"}
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          hasGap={true}
          className={classNames(defaultcss.all, sty.freeBox, {
            [sty.freeBox__submitted]: hasVariant(
              variants,
              "submitted",
              "submitted"
            )
          })}
        >
          <input
            data-plasmic-name={"name"}
            data-plasmic-override={overrides.name}
            className={classNames(defaultcss.input, sty.name)}
            placeholder={"NAME" as const}
            size={1 as const}
            type={"text" as const}
          />

          <div
            data-plasmic-name={"nameError"}
            data-plasmic-override={overrides.nameError}
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.nameError
            )}
          >
            {"Enter some text"}
          </div>

          <input
            data-plasmic-name={"email"}
            data-plasmic-override={overrides.email}
            className={classNames(defaultcss.input, sty.email)}
            placeholder={"EMAIL" as const}
            size={1 as const}
            type={"text" as const}
          />

          <div
            data-plasmic-name={"emailError"}
            data-plasmic-override={overrides.emailError}
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.emailError
            )}
          >
            {"Enter some text"}
          </div>

          <input
            data-plasmic-name={"phone"}
            data-plasmic-override={overrides.phone}
            className={classNames(defaultcss.input, sty.phone)}
            placeholder={"PHONE (optional)" as const}
            size={1 as const}
            type={"text" as const}
          />

          <div
            data-plasmic-name={"phoneError"}
            data-plasmic-override={overrides.phoneError}
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.phoneError
            )}
          >
            {"Enter some text"}
          </div>

          <textarea
            data-plasmic-name={"message"}
            data-plasmic-override={overrides.message}
            className={classNames(defaultcss.textarea, sty.message)}
            placeholder={"Message" as const}
          />

          <div
            data-plasmic-name={"messageError"}
            data-plasmic-override={overrides.messageError}
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.messageError
            )}
          >
            {"Enter some text"}
          </div>

          <SubmitButton
            data-plasmic-name={"submitButton"}
            data-plasmic-override={overrides.submitButton}
            className={classNames("__wab_instance", sty.submitButton)}
          />
        </p.Stack>
      ) : null}
      {(hasVariant(variants, "submitted", "submitted") ? true : false) ? (
        <FormThankYou
          data-plasmic-name={"formThankYou"}
          data-plasmic-override={overrides.formThankYou}
          className={classNames("__wab_instance", sty.formThankYou, {
            [sty.formThankYou__submitted]: hasVariant(
              variants,
              "submitted",
              "submitted"
            )
          })}
        />
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "freeBox",
    "name",
    "nameError",
    "email",
    "emailError",
    "phone",
    "phoneError",
    "message",
    "messageError",
    "submitButton",
    "formThankYou"
  ],
  freeBox: [
    "freeBox",
    "name",
    "nameError",
    "email",
    "emailError",
    "phone",
    "phoneError",
    "message",
    "messageError",
    "submitButton"
  ],
  name: ["name"],
  nameError: ["nameError"],
  email: ["email"],
  emailError: ["emailError"],
  phone: ["phone"],
  phoneError: ["phoneError"],
  message: ["message"],
  messageError: ["messageError"],
  submitButton: ["submitButton"],
  formThankYou: ["formThankYou"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  name: "input";
  nameError: "div";
  email: "input";
  emailError: "div";
  phone: "input";
  phoneError: "div";
  message: "textarea";
  messageError: "div";
  submitButton: typeof SubmitButton;
  formThankYou: typeof FormThankYou;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContactForm__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContactForm__VariantsArgs;
    args?: PlasmicContactForm__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicContactForm__Fetches;
  } & Omit<PlasmicContactForm__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicContactForm__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicContactForm__ArgProps,
      internalVariantPropNames: PlasmicContactForm__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicContactForm__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContactForm";
  } else {
    func.displayName = `PlasmicContactForm.${nodeName}`;
  }
  return func;
}

export const PlasmicContactForm = Object.assign(
  // Top-level PlasmicContactForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    _name: makeNodeComponent("name"),
    nameError: makeNodeComponent("nameError"),
    email: makeNodeComponent("email"),
    emailError: makeNodeComponent("emailError"),
    phone: makeNodeComponent("phone"),
    phoneError: makeNodeComponent("phoneError"),
    message: makeNodeComponent("message"),
    messageError: makeNodeComponent("messageError"),
    submitButton: makeNodeComponent("submitButton"),
    formThankYou: makeNodeComponent("formThankYou"),

    // Metadata about props expected for PlasmicContactForm
    internalVariantProps: PlasmicContactForm__VariantProps,
    internalArgProps: PlasmicContactForm__ArgProps
  }
);

export default PlasmicContactForm;
/* prettier-ignore-end */
