// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eV7Xi9hgseajGR8GcVFgnT
// Component: DzjLF3G6lYSWQc
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ContactForm from "../../ContactForm"; // plasmic-import: ys1dDALBqW2Dr/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_clove_website.module.css"; // plasmic-import: eV7Xi9hgseajGR8GcVFgnT/projectcss
import * as sty from "./PlasmicContactCard.module.css"; // plasmic-import: DzjLF3G6lYSWQc/css

export type PlasmicContactCard__VariantMembers = {};

export type PlasmicContactCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicContactCard__VariantsArgs;
export const PlasmicContactCard__VariantProps = new Array<VariantPropType>();

export type PlasmicContactCard__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicContactCard__ArgsType;
export const PlasmicContactCard__ArgProps = new Array<ArgPropType>("children");

export type PlasmicContactCard__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
  contactForm?: p.Flex<typeof ContactForm>;
};

export interface DefaultContactCardProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicContactCard__RenderFunc(props: {
  variants: PlasmicContactCard__VariantsArgs;
  args: PlasmicContactCard__ArgsType;
  overrides: PlasmicContactCard__OverridesType;
  dataFetches?: PlasmicContactCard__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box)}
      >
        {p.renderPlasmicSlot({
          defaultContents:
            "Ready to join the movement or have questions? Get in touch!",
          value: args.children,
          className: classNames(sty.slotChildren)
        })}
      </div>

      <ContactForm
        data-plasmic-name={"contactForm"}
        data-plasmic-override={overrides.contactForm}
        className={classNames("__wab_instance", sty.contactForm)}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box", "contactForm"],
  box: ["box"],
  contactForm: ["contactForm"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
  contactForm: typeof ContactForm;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContactCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContactCard__VariantsArgs;
    args?: PlasmicContactCard__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicContactCard__Fetches;
  } & Omit<PlasmicContactCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicContactCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicContactCard__ArgProps,
      internalVariantPropNames: PlasmicContactCard__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicContactCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContactCard";
  } else {
    func.displayName = `PlasmicContactCard.${nodeName}`;
  }
  return func;
}

export const PlasmicContactCard = Object.assign(
  // Top-level PlasmicContactCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    contactForm: makeNodeComponent("contactForm"),

    // Metadata about props expected for PlasmicContactCard
    internalVariantProps: PlasmicContactCard__VariantProps,
    internalArgProps: PlasmicContactCard__ArgProps
  }
);

export default PlasmicContactCard;
/* prettier-ignore-end */
