// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eV7Xi9hgseajGR8GcVFgnT
// Component: hGvVhufbV8OeD
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_clove_website.module.css"; // plasmic-import: eV7Xi9hgseajGR8GcVFgnT/projectcss
import * as sty from "./PlasmicStartedButton.module.css"; // plasmic-import: hGvVhufbV8OeD/css

export type PlasmicStartedButton__VariantMembers = {};

export type PlasmicStartedButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicStartedButton__VariantsArgs;
export const PlasmicStartedButton__VariantProps = new Array<VariantPropType>();

export type PlasmicStartedButton__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicStartedButton__ArgsType;
export const PlasmicStartedButton__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicStartedButton__OverridesType = {
  root?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultStartedButtonProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicStartedButton__RenderFunc(props: {
  variants: PlasmicStartedButton__VariantsArgs;
  args: PlasmicStartedButton__ArgsType;
  overrides: PlasmicStartedButton__OverridesType;
  dataFetches?: PlasmicStartedButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.PlasmicLink
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(defaultcss.all, sty.link)}
        component={Link}
        href={"#go" as const}
        platform={"nextjs"}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Get Started ➔",
          value: args.children,
          className: classNames(sty.slotChildren)
        })}
      </p.PlasmicLink>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStartedButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStartedButton__VariantsArgs;
    args?: PlasmicStartedButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicStartedButton__Fetches;
  } & Omit<PlasmicStartedButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicStartedButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicStartedButton__ArgProps,
      internalVariantPropNames: PlasmicStartedButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicStartedButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStartedButton";
  } else {
    func.displayName = `PlasmicStartedButton.${nodeName}`;
  }
  return func;
}

export const PlasmicStartedButton = Object.assign(
  // Top-level PlasmicStartedButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicStartedButton
    internalVariantProps: PlasmicStartedButton__VariantProps,
    internalArgProps: PlasmicStartedButton__ArgProps
  }
);

export default PlasmicStartedButton;
/* prettier-ignore-end */
