// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eV7Xi9hgseajGR8GcVFgnT
// Component: srr7ZVIUQAh-6
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_clove_website.module.css"; // plasmic-import: eV7Xi9hgseajGR8GcVFgnT/projectcss
import * as sty from "./PlasmicSubmitButton.module.css"; // plasmic-import: srr7ZVIUQAh-6/css

export type PlasmicSubmitButton__VariantMembers = {};

export type PlasmicSubmitButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicSubmitButton__VariantsArgs;
export const PlasmicSubmitButton__VariantProps = new Array<VariantPropType>();

export type PlasmicSubmitButton__ArgsType = {};
type ArgPropType = keyof PlasmicSubmitButton__ArgsType;
export const PlasmicSubmitButton__ArgProps = new Array<ArgPropType>();

export type PlasmicSubmitButton__OverridesType = {
  root?: p.Flex<"button">;
};

export interface DefaultSubmitButtonProps {
  className?: string;
}

function PlasmicSubmitButton__RenderFunc(props: {
  variants: PlasmicSubmitButton__VariantsArgs;
  args: PlasmicSubmitButton__ArgsType;
  overrides: PlasmicSubmitButton__OverridesType;
  dataFetches?: PlasmicSubmitButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.button,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"SUBMIT"}
    </button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSubmitButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSubmitButton__VariantsArgs;
    args?: PlasmicSubmitButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicSubmitButton__Fetches;
  } & Omit<PlasmicSubmitButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSubmitButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSubmitButton__ArgProps,
      internalVariantPropNames: PlasmicSubmitButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicSubmitButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSubmitButton";
  } else {
    func.displayName = `PlasmicSubmitButton.${nodeName}`;
  }
  return func;
}

export const PlasmicSubmitButton = Object.assign(
  // Top-level PlasmicSubmitButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSubmitButton
    internalVariantProps: PlasmicSubmitButton__VariantProps,
    internalArgProps: PlasmicSubmitButton__ArgProps
  }
);

export default PlasmicSubmitButton;
/* prettier-ignore-end */
