// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eV7Xi9hgseajGR8GcVFgnT
// Component: L0jfkkzI6NSWde
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_clove_website.module.css"; // plasmic-import: eV7Xi9hgseajGR8GcVFgnT/projectcss
import * as sty from "./PlasmicPartnerCard.module.css"; // plasmic-import: L0jfkkzI6NSWde/css

export type PlasmicPartnerCard__VariantMembers = {};

export type PlasmicPartnerCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicPartnerCard__VariantsArgs;
export const PlasmicPartnerCard__VariantProps = new Array<VariantPropType>();

export type PlasmicPartnerCard__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  dest?: string | PageHref;
};

type ArgPropType = keyof PlasmicPartnerCard__ArgsType;
export const PlasmicPartnerCard__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "dest"
);

export type PlasmicPartnerCard__OverridesType = {
  root?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultPartnerCardProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  dest?: string | PageHref;
  className?: string;
}

function PlasmicPartnerCard__RenderFunc(props: {
  variants: PlasmicPartnerCard__VariantsArgs;
  args: PlasmicPartnerCard__ArgsType;
  overrides: PlasmicPartnerCard__OverridesType;
  dataFetches?: PlasmicPartnerCard__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.PlasmicLink
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      component={Link}
      href={args.dest}
      platform={"nextjs"}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox__rDkbk)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__xiQtj)}
              role={"img"}
            />
          ),

          value: args.children
        })}

        <div className={classNames(defaultcss.all, sty.freeBox__zSjmD)}>
          {p.renderPlasmicSlot({
            defaultContents: "Shop 1301",
            value: args.slot,
            className: classNames(sty.slotSlot)
          })}
        </div>
      </p.Stack>
    </p.PlasmicLink>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPartnerCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPartnerCard__VariantsArgs;
    args?: PlasmicPartnerCard__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicPartnerCard__Fetches;
  } & Omit<PlasmicPartnerCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPartnerCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPartnerCard__ArgProps,
      internalVariantPropNames: PlasmicPartnerCard__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicPartnerCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPartnerCard";
  } else {
    func.displayName = `PlasmicPartnerCard.${nodeName}`;
  }
  return func;
}

export const PlasmicPartnerCard = Object.assign(
  // Top-level PlasmicPartnerCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicPartnerCard
    internalVariantProps: PlasmicPartnerCard__VariantProps,
    internalArgProps: PlasmicPartnerCard__ArgProps
  }
);

export default PlasmicPartnerCard;
/* prettier-ignore-end */
