// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eV7Xi9hgseajGR8GcVFgnT
// Component: QGA80RgFGLd73
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_clove_website.module.css"; // plasmic-import: eV7Xi9hgseajGR8GcVFgnT/projectcss
import * as sty from "./PlasmicInfoCard.module.css"; // plasmic-import: QGA80RgFGLd73/css

export type PlasmicInfoCard__VariantMembers = {
  colors: "green" | "offWhite" | "purple";
  mobile: "mobile";
};

export type PlasmicInfoCard__VariantsArgs = {
  colors?: SingleChoiceArg<"green" | "offWhite" | "purple">;
  mobile?: SingleBooleanChoiceArg<"mobile">;
};

type VariantPropType = keyof PlasmicInfoCard__VariantsArgs;
export const PlasmicInfoCard__VariantProps = new Array<VariantPropType>(
  "colors",
  "mobile"
);

export type PlasmicInfoCard__ArgsType = {
  children?: React.ReactNode;
  title?: React.ReactNode;
};

type ArgPropType = keyof PlasmicInfoCard__ArgsType;
export const PlasmicInfoCard__ArgProps = new Array<ArgPropType>(
  "children",
  "title"
);

export type PlasmicInfoCard__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultInfoCardProps {
  children?: React.ReactNode;
  title?: React.ReactNode;
  colors?: SingleChoiceArg<"green" | "offWhite" | "purple">;
  mobile?: SingleBooleanChoiceArg<"mobile">;
  className?: string;
}

function PlasmicInfoCard__RenderFunc(props: {
  variants: PlasmicInfoCard__VariantsArgs;
  args: PlasmicInfoCard__ArgsType;
  overrides: PlasmicInfoCard__OverridesType;
  dataFetches?: PlasmicInfoCard__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box___3BgDa, {
          [sty.box__colors_green___3BgDaRNtSu]: hasVariant(
            variants,
            "colors",
            "green"
          ),
          [sty.box__colors_offWhite___3BgDa8TPcq]: hasVariant(
            variants,
            "colors",
            "offWhite"
          ),
          [sty.box__colors_purple___3BgDam4Bk3]: hasVariant(
            variants,
            "colors",
            "purple"
          ),
          [sty.box__mobile___3BgDaqRfMv]: hasVariant(
            variants,
            "mobile",
            "mobile"
          )
        })}
      >
        <div
          className={classNames(defaultcss.all, sty.box__sw2T8, {
            [sty.box__mobile__sw2T8QRfMv]: hasVariant(
              variants,
              "mobile",
              "mobile"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <span>
                <span style={{ fontStyle: "italic" }}>{"01"}</span>
              </span>
            ),
            value: args.children,
            className: classNames(sty.slotChildren, {
              [sty.slotChildren__mobile]: hasVariant(
                variants,
                "mobile",
                "mobile"
              )
            })
          })}
        </div>

        {p.renderPlasmicSlot({
          defaultContents: "Some long header text",
          value: args.title,
          className: classNames(sty.slotTitle, {
            [sty.slotTitle__colors_purple]: hasVariant(
              variants,
              "colors",
              "purple"
            )
          })
        })}
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInfoCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInfoCard__VariantsArgs;
    args?: PlasmicInfoCard__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicInfoCard__Fetches;
  } & Omit<PlasmicInfoCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicInfoCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicInfoCard__ArgProps,
      internalVariantPropNames: PlasmicInfoCard__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicInfoCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInfoCard";
  } else {
    func.displayName = `PlasmicInfoCard.${nodeName}`;
  }
  return func;
}

export const PlasmicInfoCard = Object.assign(
  // Top-level PlasmicInfoCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicInfoCard
    internalVariantProps: PlasmicInfoCard__VariantProps,
    internalArgProps: PlasmicInfoCard__ArgProps
  }
);

export default PlasmicInfoCard;
/* prettier-ignore-end */
