// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eV7Xi9hgseajGR8GcVFgnT
// Component: UP0pQhrQy0dXu
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_clove_website.module.css"; // plasmic-import: eV7Xi9hgseajGR8GcVFgnT/projectcss
import * as sty from "./PlasmicCheckmarkText.module.css"; // plasmic-import: UP0pQhrQy0dXu/css

import Icons8OksvgIcon from "./icons/PlasmicIcon__Icons8Oksvg"; // plasmic-import: BJjXYf54QGzaHz/icon

export type PlasmicCheckmarkText__VariantMembers = {};

export type PlasmicCheckmarkText__VariantsArgs = {};
type VariantPropType = keyof PlasmicCheckmarkText__VariantsArgs;
export const PlasmicCheckmarkText__VariantProps = new Array<VariantPropType>();

export type PlasmicCheckmarkText__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCheckmarkText__ArgsType;
export const PlasmicCheckmarkText__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicCheckmarkText__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultCheckmarkTextProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicCheckmarkText__RenderFunc(props: {
  variants: PlasmicCheckmarkText__VariantsArgs;
  args: PlasmicCheckmarkText__ArgsType;
  overrides: PlasmicCheckmarkText__OverridesType;
  dataFetches?: PlasmicCheckmarkText__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Icons8OksvgIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, sty.svg)}
        role={"img"}
      />

      {p.renderPlasmicSlot({
        defaultContents: "Reduce your environmental impacts",
        value: args.children,
        className: classNames(sty.slotChildren)
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCheckmarkText__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCheckmarkText__VariantsArgs;
    args?: PlasmicCheckmarkText__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCheckmarkText__Fetches;
  } & Omit<PlasmicCheckmarkText__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCheckmarkText__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCheckmarkText__ArgProps,
      internalVariantPropNames: PlasmicCheckmarkText__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCheckmarkText__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCheckmarkText";
  } else {
    func.displayName = `PlasmicCheckmarkText.${nodeName}`;
  }
  return func;
}

export const PlasmicCheckmarkText = Object.assign(
  // Top-level PlasmicCheckmarkText renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicCheckmarkText
    internalVariantProps: PlasmicCheckmarkText__VariantProps,
    internalArgProps: PlasmicCheckmarkText__ArgProps
  }
);

export default PlasmicCheckmarkText;
/* prettier-ignore-end */
