// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicTeamMembers,
  DefaultTeamMembersProps
} from "./plasmic/copy_of_clove_website/PlasmicTeamMembers";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface TeamMembersProps extends Omit<DefaultTeamMembersProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultTeamMembersProps altogether and have
// total control over the props for your component.
interface TeamMembersProps extends DefaultTeamMembersProps {}

function TeamMembers_(props: TeamMembersProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicTeamMembers to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicTeamMembers are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all TeamMembersProps here, but feel free
  // to do whatever works for you.

  return <PlasmicTeamMembers root={{ ref }} {...props} />;
}

const TeamMembers = React.forwardRef(TeamMembers_);
export default TeamMembers;
